spring:
  application:
    name: cardservice

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jackson:
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN: true

server:
  port: 8087

card:
  kafka:
    topic: card-events

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

account:
  service:
    url: http://localhost:8080

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com.bank.cardservice.client: DEBUG
