server:
  port: 8094

#debug: true

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable automatic routing using Eureka
          lower-case-service-id: true
      # optional: routes if you want custom paths
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,
        - id: account_service
          uri: lb://account_service
          predicates:
            - Path=/api/accounts/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/accounts/**
        - id: cardservice
          uri: lb://cardservice
          predicates:
            - Path=/api/cards/**
        - id: account_service
          uri: lb://account_service
          predicates:
            - Path=/api/accounts/**
        - id: transactionservice
          uri: lb://transactionservice
          predicates:
            - Path=/api/service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
