#spring:
#  application:
#    name: transaction
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
#    username: emp123
#    password: emp123
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.OracleDialect 
#server:
#  port: 8001
#  servlet:
#    context-path: /transactions
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR
#
#
#


spring:
  application:
    name: transaction
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: emp123
    password: emp123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect 

server:
  port: 8001
  servlet:
    context-path: /transactions

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
